name: black

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run black
        run: uv run black --check airo_ipc
